spring:
  application:
    name: osc-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/order_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: osc-config
      profile: dev
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

